# Generated by Django 5.2 on 2025-04-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_alter_actor_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='image_url',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image_url',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
